# Generated by Django 3.1.7 on 2021-04-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='profile_picture/'),
            preserve_default=False,
        ),
    ]
